### ISSUE TITLE
Create your personal webpage

### ISSUE THREAD

**Issue by bbilter** [bbilter/alumbook#1]
Create your personal name webpage in the gradbook app and a link to it from the main page.

Read the CSC495_README.txt for additional information.

**Comment by brettjbush** [comment]
Hey Brad,

I'll get this started. I'll email if I have any questions.

Thanks,
Brett Bush

**Comment by vbashorun** [comment]
Hey, what's this about? I checked the readme file mentioned here but it didn't have any information regarding this.

**Comment by bbilter** [comment]
That was an exercise I tried to get everyone to do way back when in order to get familiarized with git and rails.  Remember we had a lab on rails but the lab didn't really work.  this was my own attempt at a lab to give our team a leg up.
Only a few people did it unfortunately.
Date: Tue, 2 Jun 2015 06:15:01 -0700
